name: Update README

on:
  schedule:
    - cron: "0 16 * * *" # Runs every day at 4:00 PM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests dotenv

      - name: Run script
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: python .github/scripts/update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name 'YashwanthReddyVeesarapu'
          git config --global user.email 'yashwanthreddyveesarapu@gmail.com'
          git add README.md
          git commit -m 'Update README with latest job listings'
          git push
